# Generated by Django 5.1.6 on 2025-02-13 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TB2', 'tb2'), ('TB3', 'tb3'), ('AKINCI', 'akıncı'), ('KIZILELMA', 'kızılelma')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('default_part_type', models.CharField(blank=True, choices=[('Kanat', 'Kanat Takımı'), ('Gövde', 'Gövde Takımı'), ('Kuyruk', 'Kuyruk Takımı'), ('Aviyonik', 'Aviyonik Takımı'), ('Montaj', 'Montaj Takımı')], max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IhaKontrol.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft_produced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IhaKontrol.aircraft')),
                ('parts_used', models.ManyToManyField(to='IhaKontrol.part')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IhaKontrol.team')),
            ],
        ),
    ]
