# Generated by Django 5.1.6 on 2025-02-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaKontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IhaKontrol.team'),
        ),
    ]
